### PR TITLE
Fixing brocken install_gnparser() #17

### PR DESCRIPTION
**Pull request by AlbanSagouis**
## Description
`install_gnparser()` now specifically selects the last releases for the user's system and ignores `clib` releases

## Related Issue
#17 

## Warning
`rgnparser:::install_gnparser_bin()` has high chances to throw a warning but succeed in the next step of the loop so maybe warning should be shown only if all steps of the loops fail?

### CODE REVIEW

**Comment by joelnitta** [comment]
This installs on my machine, so looks good from here.

To make sure `install_gnparser()` works, I set `force = TRUE` in `test-install_gnparser.R`, and made it run before other tests so that all tests are run on the most recent version of gnparser.

@AlbanSagouis  can you explain why `rgnparser:::install_gnparser_bin()` has a high chance of issuing a warning, and what line the warning comes from?

**Comment by AlbanSagouis** [comment]
> @AlbanSagouis can you explain why `rgnparser:::install_gnparser_bin()` has a high chance of issuing a warning, and what line the warning comes from?

In row 111 of install_gnparser.R a loop is opened over the potential directories where the downloaded executable might be located. The potential directories are given by `rgnparser:::bin_paths()` which in my case gives a length 3 vector:
```
>  bin_paths()
[1] "/usr/local/bin"                         "~/Library/Application Support/gnparser" ""
```
In row 113, when `file.copy()` tries the first potential directory, it fails and throw a warning but next step of the loop, `file.copy()` succeeds and installation works. I find the warning misleading in this situation.

**Comment by joelnitta** [comment]
@AlbanSagouis I silenced the warning. Can you try it and see if it works for you now?

**Comment by AlbanSagouis** [comment]
Hi Joel,
I ran the code but an error is thrown in the warning handling:
```
Error in if (grep("Not a directory", conditionMessage(w), ignore.case = TRUE)) invokeRestart("muffleWarning") :
argument is of length zero
```
It seems that it is `w` that is or length 0.

**Comment by AlbanSagouis** [comment]
The warning sent by `file.copy` is the following: 
```
 > success <- file.copy(exec, destdir, overwrite = TRUE)
Warning message:
In file.copy(exec, destdir, overwrite = TRUE) :
  problem copying ./gnparser to /usr/local/bin/gnparser: Permission denied
```

**Comment by joelnitta** [comment]
That looks good to me, but something changed so that now `install_gnparser_bin()` is failing on Windows.

Compare these recent checks.

Successful: https://github.com/ropensci/rgnparser/actions/runs/3913203429/jobs/6688813846#step:10:51
- installs to `C:\Users\runneradmin\AppData\Roaming\gnparser`

Failed (most recent build): https://github.com/ropensci/rgnparser/actions/runs/3950934884/jobs/6764138763#step:10:52
- tries to install to `C:\Users\runneradmin\AppData\Roaming/gnparser`

Apparently somehow a back-slash got switched to a forward-slash...

**Comment by AlbanSagouis** [comment]
> That looks good to me, but something changed so that now `install_gnparser_bin()` is failing on Windows.
> 
> Compare these recent checks.
> 
> Successful: https://github.com/ropensci/rgnparser/actions/runs/3913203429/jobs/6688813846#step:10:51
> 
>     * installs to `C:\Users\runneradmin\AppData\Roaming\gnparser`
> 
> 
> Failed (most recent build): https://github.com/ropensci/rgnparser/actions/runs/3950934884/jobs/6764138763#step:10:52
> 
>     * tries to install to `C:\Users\runneradmin\AppData\Roaming/gnparser`
> 
> 
> Apparently somehow a back-slash got switched to a forward-slash...

Thanks for looking into it. I don't find where my changes affect this and I don't even find exactly where this path is built. 
I guess it is between `rgnparser:::bin_path()` and `rgnparser:::pkg_file()`.

**Comment by AlbanSagouis** [comment]
I just tried this version of `rgnparser::install_gnparser()` on a Linux system and the installed failed because when the following function is ran, it fails:
```
dir_writable <- function(x) utils::file_test("-w", x)
```
gives
```
Error in utils::file_test("-w", getwd()) : test '-w' is not available
```

**Comment by AlbanSagouis** [comment]
I'm thinking that we should first release a patch and submit it to CRAN so that new users can easily install gnparser and if `rgnparser:::install_gnparser_bin()` throws a warning, this is not important.

So we could just revert back to [85c1381](https://github.com/ropensci/rgnparser/pull/21/commits/85c1381853f6cf73afa483306035d2a49f4b4c1c), what do you think?

**Pull request merged**
